name: Python UI Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  ui-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "requirements.txt not found, installing basic packages"
            pip install pytest selenium webdriver-manager allure-pytest pytest-rerunfailures
          fi

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip xvfb libxi6 libgbm-dev libnss3-dev libxss1 libasound2t64 libatk-bridge2.0-0 default-jre

      - name: Install Google Chrome
        run: |
          wget -q -O /tmp/chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt-get install -y /tmp/chrome.deb
          sudo apt --fix-broken install -y
          google-chrome --version

      - name: Install ChromeDriver
        run: |
          python -c "from webdriver_manager.chrome import ChromeDriverManager; ChromeDriverManager().install()"

      - name: Create default pytest.ini if not exists
        run: |
          if [ ! -f pytest.ini ]; then
            echo "[pytest]" > pytest.ini
            echo "testpaths = tests" >> pytest.ini
            echo "python_files = test_*.py" >> pytest.ini
            echo "python_classes = Test*" >> pytest.ini
            echo "python_functions = test_*" >> pytest.ini
            echo "addopts = -v --tb=short --reruns 1 --reruns-delay 2" >> pytest.ini
            echo "junit_family = xunit2" >> pytest.ini
            echo "junit_suite_name = UI Tests" >> pytest.ini
            echo "Created default pytest.ini"
          fi

      - name: Prepare reports directories
        run: |
          mkdir -p allure-results
          mkdir -p allure-report

      - name: Run UI tests with pytest
        env:
          HEADLESS: "true"
          PYTHONUNBUFFERED: "1"
        run: |
          export CHROME_BIN=/usr/bin/google-chrome
          export DISPLAY=:99
          Xvfb :99 -screen 0 1920x1080x24 &
          echo "Running tests in headless mode"
          pytest -v --junitxml=junit-results.xml --alluredir=allure-results --reruns=1 --reruns-delay=2 || true

      - name: Check if test results exist
        run: |
          if [ -f junit-results.xml ]; then
            echo "JUnit results found"
            cat junit-results.xml
          else
            echo "JUnit results not found - creating empty file"
            echo '<?xml version="1.0" encoding="utf-8"?><testsuite errors="0" failures="0" name="pytest" skipped="0" tests="0" time="0.0"></testsuite>' > junit-results.xml
          fi

      - name: Upload JUnit test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          path: junit-results.xml

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Install Allure CLI
        if: always()
        run: |
          sudo apt-get install -y default-jre
          wget -q -O allure-2.21.0.tgz https://github.com/allure-framework/allure2/releases/download/2.21.0/allure-2.21.0.tgz
          sudo tar -zxvf allure-2.21.0.tgz -C /opt/
          sudo ln -s /opt/allure-2.21.0/bin/allure /usr/bin/allure
          allure --version

      - name: Generate Allure report
        if: always()
        run: |
          if [ -d allure-results ] && [ "$(ls -A allure-results)" ]; then
            allure generate allure-results -o allure-report --clean
            echo "Allure report generated"
          else
            echo "No Allure results found"
          fi

      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Publish test results
        if: always() && github.event_name != 'pull_request'
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: junit-results.xml
